version: '3.8'

services:
  graphrag:
    build: .
    container_name: graphrag
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY:-}
      - LANGSMITH_PROJECT=graphrag-project
      - LANGSMITH_TRACING=${LANGSMITH_TRACING:-false}
      - ENABLE_MONITORING=${ENABLE_MONITORING:-true}
      - MONITORING_CONFIG_PATH=config/monitoring.yaml
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    depends_on:
      - milvus
      - neo4j
    restart: unless-stopped

  milvus:
    image: milvusdb/milvus:v2.2.9
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./data/milvus_data:/var/lib/milvus/data
      - ./config/docker/milvus/conf:/var/lib/milvus/conf
      - ./logs/milvus:/var/lib/milvus/logs
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    restart: unless-stopped

  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j_data:/data
      - ./logs/neo4j:/logs
      - ./config/docker/neo4j/conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
    restart: unless-stopped